package com.ids.qasemti.utils

object ApiParameters {
    const val DATA = "data"
    const val USER_ID = "user_id"
    const val FIRST_NAME="first_name"
    const val MIDDLE_NAME = "middle_name"
    const val LAST_NAME ="last_name"
    const val EMAIL = "email"
    const val MOBILE_NUMBER = "mobile_number"
    const val ALTERNATE_NUMBER ="altr_numb"
    const val CIVIL_ID = "civil_id"
    const val GENDER = "gender"
    const val DATE_OF_BIRTH ="date_of_birth"
    const val ROLE = "role"
    const val ADDRESS = "address"
    const val LATITUDE = "latitude"
    const val LONGITUDE ="longtitude"
    const val ACCOUNT_NUMBER = "account_number"
    const val BANK_NAME ="bank_name"
    const val BANK_ID ="bank_id"
    const val BANK_BRANCH = "bank_branch"
    const val IBAN = "iban"
    const val PROFILE_PIC="profile_pic"
    const val CIVIL_ID_ATTACH="civil_id_attach"
    const val CATEGORY = "category"

    const val PRODUCT_NAME = "product_name"
    const val SIZE_CAPACITY = "size-capacity"
    const val TYPE = "type"
    const val STOCK_STATUS = "stock_status"
    const val DESCRIPTION = "description"
    const val PRODUCT_DESC = "product_desc"
    const val GALLERY = "gallery[]"
    const val PRODUCT_ID = "product_id"
    const val LANGUAGE = "language"
    const val FILE = "file"
    const val FILE_NAME = "file_name"
    const val FILE_ID = "file_id"
}
